name: 'Auto Convert PDF to Image PDF'

on:
  workflow_dispatch:
  push:

permissions: write-all

jobs:
  Convert:
    name: Convert
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
      
    - name: Cache
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install dependencies
      run: |
        python -m venv ./.venv
        . ./.venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Convert
      run: |
        . ./.venv/bin/activate
        python ./src/github_action_runner.py

    - name: Get workflow info
      run: |
        {
          echo 'workflow_info<<EOF'
          cat ./src/workflow_info.json
          echo EOF
        } >> "$GITHUB_ENV"

    - name: Zip
      run: |
        cd ./result
        zip -r result.zip ./*
        echo ${{ fromJson(env.workflow_info).publish }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ fromJson(env.workflow_info).tag }}
        name: ${{ fromJson(env.workflow_info).title }}
        body: ${{ fromJson(env.workflow_info).body }}
        files: ${{ fromJson(env.workflow_info).zip-file }}
      if: fromJson(env.workflow_info).publish == 'true'

    - name: Git commit
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    