name: 'Auto Convert PDF to Image PDF'

on:
  workflow_dispatch:
  push:

permissions: write-all

jobs:
  Convert:
    name: Convert
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: fufuhu/get-commit-id
      id: get_commit_id

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
      
    - name: Cache
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install dependencies
      run: |
        python -m venv ./.venv
        . ./.venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Convert
      run: |
        . ./.venv/bin/activate
        python ./src/github_action_runner.py

    - name: Get result files
      id: get_result_files
      run: |
        {
          echo 'result_files<<EOF'
          ls ./result
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

    - name: zip
      run: |
        cd ./result
        zip -r result.zip ./*

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./result/result.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        # tag_name: ${{ steps.get_commit_id.outputs.commit_id }}
        # release_name: ${{ steps.get_commit_id.outputs.commit_id }}
        release_notes: ${{ steps.get_result_files.outputs.result_files }}
    